spring:
  application:
    name: ProyectoFinal
  session:
    store-type: mongodb
  data:
    mongodb:
      database: ProyectoFinal
      host: localhost
      port: 27017
server:
  port: 8080
  error:
    include-message: always
